name: Commit Utsc

on:
    workflow_call:
        inputs:
          environment:
            description: GCP Project
            type: string
            default: platform-staging
            required: true
    workflow_dispatch:
        inputs:
          environment:
            description: GCP Project
            type: environment
            default: platform-staging
            required: true

jobs:
  commit_utsc:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'platform-staging' }}

    steps:
      - name: "Setup Git Config"
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.DEPLOY_APP_ID }}
          private-key: ${{ secrets.DEPLOY_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: "Check out repository"
        uses: actions/checkout@v3
        with:
          lfs: true
          persist-credentials: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: "@easy-games"

      - name: Install Dependencies
        run: |
          npm ci

      - name: "Build Npm Project"
        run: |
          npm run bundle

      - name: Checkout Airship Repo
        uses: actions/checkout@v3
        with:
          repository: easy-games/airship
          path: __airship
          ref: main
          token: ${{ steps.generate-token.outputs.token }}

      - name: Commit New Utsc
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B $COMMIT_HASH)

          cp dist/utsc.js __airship/Editor/TypescriptCompiler~/utsc.js
          cd __airship
          chmod +x Editor/TypescriptCompiler~/utsc.js
          git add Editor/TypescriptCompiler~/utsc.js
          if git diff --staged --exit-code; then
            echo "No changes to commit"
          else
            git commit -am "Automated UTSC push.
              Reference: https://github.com/easy-games/unity-ts/commit/$COMMIT_HASH
              Message: $COMMIT_MESSAGE"
            git push origin main
          fi
