name: Publish Package

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: GCP Project
        type: environment
        default: platform-staging
        required: true

jobs:
  publish-npm:
    environment: ${{ inputs.environment || 'platform-staging' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          echo "@easy-games:registry=${{vars.REGISTRY_URL}}" > .npmrc
          cat .npmrc
          npm i
          npm i -g npm-cli-login
          NPM_USER=deploy NPM_PASS=${{secrets.PACKAGE_DEPLOY_PASSWORD}} NPM_REGISTRY=${{vars.REGISTRY_URL}} NPM_EMAIL=engineering@easy.gg npm-cli-login

          npm --no-git-tag-version version "$(cat package.json | grep '"version":' | sed -E 's/.*"version": "([0-9]+\.[0-9]+\.)[0-9]+".*/\1/')${{github.run_number}}"
          npm publish --registry ${{vars.REGISTRY_URL}}
