name: Publish

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.3.4

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.0
              with:
                  node-version: 16
                  registry-url: "https://npm.pkg.github.com/"
                  scope: "@easy-games"

            # Runs a single command using the runners shell
            - name: Install Dependencies
              run: |
                  npm ci
              env:
                  EASY_AUTH_TOKEN: ${{ secrets.PULL_PACKAGE_PAT }}

            - name: Publish
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "noreply@github.com"
                  npm --no-git-tag-version version $(cat package.json | sed -n '/"version": "*/ { s///; s/".*//; p; q; }')-${{github.run_number}}
                  npm publish
              env:
                  # We use EASY_AUTH_TOKEN because that's what's in the .npmrc
                  EASY_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
