name: Publish

on:
    workflow_dispatch:
        inputs:
          environment:
            description: GCP Project
            type: environment
            default: platform-staging
            required: true
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment || 'platform-staging' }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.3.4

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.4.0
              with:
                  node-version: 16
                  registry-url: 'https://registry.npmjs.org'
                  scope: "@easy-games"

            # Runs a single command using the runners shell
            - name: Install Dependencies
              run: |
                  npm ci

            - name: Publish
              run: |
                  npm --no-git-tag-version version "$(cat package.json | grep '"version":' | sed -E 's/.*"version": "([0-9]+\.[0-9]+\.)[0-9]+".*/\1/')${{github.run_number}}"
                  npm publish --tag ${{vars.NPM_TAG}}
              env:
                  # We use EASY_AUTH_TOKEN because that's what's in the .npmrc
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    # commit_utsc:
    #     uses: "./.github/workflows/CommitUtsc.yml"
    #     secrets: inherit
    #     with:
    #         environment: ${{ inputs.environment }}
